#!/store/app/bin/php
<?

foreach (glob($content_path . '/store/data/contents/*') as $filename) {

        $doc = new DOMDocument();
        $doc->preserveWhiteSpace = false;
        if (! $doc->load($filename)) {
                echo "Error when load content file: $filename\n";
                continue;
        }
        $scripts_element = $doc->documentElement;

        foreach ($scripts_element->childNodes as $script_xml) {
$x=$doc->saveXML();
$y=str_replace('<window left="0" top="0" right="45" bottom="768">','<window left="0" top="1" right="45" bottom="768">',$x);
$doc2=new DOMDocument();
$doc2->loadXML($y);
$doc2->save($filename.".new");
unlink($filename);
`sync`;
sleep(5);
`/store/app/bin/utils_linux/convert_content.php`;
        }
}
?>
